import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar, Sidebar } from '@/components';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className='w-screen h-screen  bg-image'
          style={{
            backgroundImage: "url('/bg_piassa.png')",
            backgroundSize: 'cover',
            backgroundPosition: 'center',
          }}
        >
          <div className='flex backdrop-blur-md'>
            <Sidebar />
            <div className='flex-1'>
              <Navbar />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
