import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar, Sidebar } from '@/components';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
//grid min-h-dvh grid-cols-1 grid-rows-[1fr_1px_auto_1px_auto] pt-26.25 lg:grid-cols-[var(--container-2xs)_2.5rem_minmax(0,1fr)_2.5rem] lg:pt-14.25 xl:grid-cols-[var(--container-2xs)_2.5rem_minmax(0,1fr)_2.5rem]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className='relative w-screen h-screen overflow-hidden'
        >
          <div
            className='absolute inset-0'
            style={{
              backgroundImage: "url('/bg_piassa.png')",
              backgroundSize: 'cover',
              backgroundPosition: 'center',
            }}
          />
          <div className='backdrop-blur-md absolute inset-0' />
          <Sidebar />
          <div className='flex flex-col w-full h-full'>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
